entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

providers:
  docker: {}

certificatesResolvers:
  myresolver:
    acme:
<<<<<<< HEAD
      email: your@mail.com
=======
      email: wessels.tobias@gmail.com
>>>>>>> 32a7b2bf42fa4af10a8b86350ed832f57ac88ca3
      storage: /data/letsencrypt.json
      httpChallenge:
        entryPoint: web
